name: 'Get tag and version'
description: 'A simple action to get the last or next tag/version to use in other actions.'
branding:
  icon: 'tag'
  color: 'gray-dark'
inputs:
  fallback:
    description: Optional. Fallback tag/version to use when no previous tag can be found. May include a valid prefix, but may also exclude it.
    required: false
    default: "0.0.0"
  increment:
    description: Optional. Increment the version number by one digit. Possible values are "major", "minor", "patch", "build" and "suffix".
    required: false
    default: "false"
  tag:
    description: Optional. Tag ref to use. Will omit the searching stage and use the supplied tag ref if its a valid match.
    required: false
    default: ""
  branch:
    description: Optional. Only search for for tags on the currently selected branch.
    required: false
    default: "false"
  prefix:
    description: Optional. The prefix to search for, and will be set for the new tags if auto-increment is enabled.
    required: false
    default: "v"
  prefixRegex:
    description: Optional. A regex sub-pattern to match multiple prefixes while looking for a match. Must also match the given prefix.
    required: false
    default: ""
  suffix:
    description: Optional. An optional suffix to search for, and will be set for new tags if auto-increment is enabled.
    required: false
    default: ""
  suffixRegex:
    description: Optional. A regex sub-pattern to match multiple suffixes while looking for a match. Must also match the given suffix.
    required: false
    default: ""
  buildNumber:
    description: 'Optional. A static build number.  Useful if the build number is provided by the environment. NOTE: Auto increment must be set to "build" or "suffix".'
    required: false
    default: ""

outputs:
  tag:
    description: 'The full tag with the prefix, version and suffix combined.'
  tag_prefix:
    description: 'The tag prefix.'
  tag_suffix:
    description: 'The tag suffix.'
  commit:
    description: 'Full git commit hash for the tag.'
  commit_short:
    description: 'Short-form git commit hash for the tag.'
  version:
    description: 'The full version, with build number.'
  version_major:
    description: 'The major version number.'
  version_minor:
    description: 'The minor version number.'
  version_patch:
    description: 'The patch version number.'
  version_build:
    description: 'The build version number.'
  date:
    description: 'An ISO 8601 format timestamp in UTC offset.'
  date_year:
    description: 'The year component of the date in UTC offset.'
  date_month:
    description: 'The month component of the date in UTC offset.'
  date_day:
    description: 'The day component of the date in UTC offset.'
  date_weekday:
    description: 'The day of the week of the date in UTC offset (e.g. Monday, Tuesday, etc.)'
  date_hours:
    description: 'The hour component of the time in UTC offset.'
  date_minutes:
    description: 'The minute component of the time in UTC offset.'
  date_seconds:
    description: 'The second component of the time in UTC offset.'
  date_milliseconds:
    description: 'The millisecond component of the time in UTC offset.'

runs:
  using: 'node16'
  main: 'main.js'
